export const SONGS = [
  "Al Green – Let's Stay Together",
  "Amy Winehouse – Valerie",
  "Andrew Bird – Measuring Cups",
  "Beck – The Golden Age",
  "Bill Withers – Ain't No Sunshine",
  "Bill Withers – Lean on Me",
  "Bob Dylan – Like a Rolling Stone",
  "Bob Marley – No Woman No Cry",
  "Bon Iver – Skinny Love",
  "Bright Eyes – First Day of My Life",
  "Bruce Springsteen – Dancing in the Dark",
  "Bruce Springsteen – I'm on Fire",
  "Coldplay – Clocks",
  "Dave Matthews Band – Ants Marching",
  "David Gray – Babylon",
  "Death Cab for Cutie – I Will Follow You Into the Dark",
  "Donny Hathaway – Jealous Guy",
  "Dr. Dog – Shadow People",
  "Eagles – Hotel California",
  "Edward Sharpe & The Magnetic Zeros – Home",
  "Elton John – Tiny Dancer",
  "Elton John – Your Song (Eb)",
  "Elvis Presley – Can't Help Falling In Love With You",
  "Eric Clapton – Lay Down Sally",
  "Eric Clapton – Layla",
  "Father John Misty – I'm Writing A Novel",
  "Feist – 1, 2, 3, 4",
  "Fleetwood Mac – Landslide",
  "Flock of Dimes – Awake for the Sunrise",
  "Foo Fighters – Everlong",
  "Geese – Cobra",
  "Goo Goo Dolls – Slide",
  "Hall & Oates – You Make My Dreams Come True",
  "Jack Johnson – Better Together",
  "James Taylor – Fire and Rain",
  "James Taylor – How Sweet It Is",
  "Jason Mraz – I'm Yours",
  "Jeff Buckley – Hallelujah",
  "John Legend – All of Me",
  "John Lennon – Imagine",
  "John Mayer – Why Georgia",
  "Johnny Cash – Folsom Prison Blues",
  "Johnny Cash – I Walk The Line",
  "Johnny Cash – Ring of Fire",
  "Josh Ritter – Girl in the War",
  "Josh Ritter – Monster Ballads",
  "Journey – Don't Stop Believin'",
  "Judy Garland – Somewhere Over the Rainbow",
  "Kings of Leon – Use Somebody",
  "Lumineers – Ho Hey",
  "Matchbox 20 – 3AM",
  "MGMT – Time to Pretend",
  "Modern English – Melt with You",
  "Mumford & Sons – I Will Wait",
  "Neil Diamond – Sweet Caroline",
  "Neil Young – Harvest Moon",
  "Neil Young – Heart of Gold",
  "Neutral Milk Hotel – In the Aeroplane Over the Sea",
  "Oasis – Wonderwall",
  "Old Crow Medicine Show – Wagon Wheel",
  "Otis Redding – Sittin' On The Dock of the Bay",
  "Pearl Jam – Betterman",
  "Radiohead – Creep",
  "Radiohead – Fake Plastic Trees",
  "Radiohead – Karma Police",
  "Ray LaMontagne – You Are the Best Thing",
  "REM – Losing My Religion",
  "Roy Orbison – Pretty Woman",
  "Sam Cooke – Wonderful World",
  "Sheryl Crow – Strong Enough",
  "Simon & Garfunkel – Me and Julio Down by the Schoolyard",
  "Simon & Garfunkel – The Sound of Silence",
  "Spoon – The Underdog",
  "Stealers Wheel – Stuck in the Middle With You",
  "Tears for Fears – Everybody Wants to Rule the World",
  "The Band – The Weight",
  "The Beatles – Come Together",
  "The Beatles – Here Comes The Sun",
  "The Beatles – In My Life",
  "The Beatles – Norwegian Wood",
  "The Beatles – Yellow Submarine",
  "The Flaming Lips – Yoshimi Battles the Pink Robots",
  "The National – Fake Empire",
  "The Postal Service – The District Sleeps Alone Tonight",
  "The Rolling Stones – Wild Horses",
  "The Temptations – My Girl",
  "Tom Petty – Free Fallin'",
  "Tom Petty – I Won't Back Down",
  "Tom Petty – Wildflowers",
  "Tom Petty – You Don't Know How It Feels",
  "Tracy Chapman – Gimme One Reason",
  "Vampire Weekend – I Stand Corrected",
  "Van Morrison – Brown Eyed Girl",
  "Van Morrison – Into the Mystic",
  "Wilco – California Stars",
  "Wilco – I'm the Man Who Loves You",
  "Wilco – Jesus, etc.",
  "Wilco – Kamera",
];
